#!/usr/bin/env ansible-playbook
---
- name: Archive api container image as a tarball
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  - ../config.yml
  tasks:
  - name: archive container image as a tarball
    shell: "docker save {{ api_container_image }} -o ./archived_image.tar"

- name: Upload docker image
  hosts: dev
  become: True
  gather_facts: no
  vars_files:
  - ../config.yml
  tasks:
  - name: copy tarball to host
    copy:
      src: ./archived_image.tar
      dest: /root/archived_image.tar

  - name: load container from tarball
    docker_image:
      name: "{{ api_container_image }}"
      load_path: /root/archived_image.tar
      state: present
      source: load
